// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024211304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Models.Procedures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcedureType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProfessorId1")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId2")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId3")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId4")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId5")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessorId6")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessorId7")
                        .HasColumnType("int");

                    b.Property<int>("ReserveExternalId")
                        .HasColumnType("int");

                    b.Property<int>("ReserveInternalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("Infrastructure.Models.Proffessors", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AcademicRank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsecutiveCounter")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastParticipationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PrevParticipationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScientificFiled")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UniIsLocal")
                        .HasColumnType("bit");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Proffessors");
                });
#pragma warning restore 612, 618
        }
    }
}
